// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQIu0G48ADQCaDqmfrDatFwTUhdQbjx0o',
    appId: '1:408784567402:web:dedda32be1df6938489e13',
    messagingSenderId: '408784567402',
    projectId: 'busks-e255d',
    authDomain: 'busks-e255d.firebaseapp.com',
    storageBucket: 'busks-e255d.appspot.com',
    measurementId: 'G-7S4S9JZ3ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPWoHKVjCjmoPxuiwmZqvpoikbMN04GI',
    appId: '1:408784567402:android:131be691d84cda19489e13',
    messagingSenderId: '408784567402',
    projectId: 'busks-e255d',
    storageBucket: 'busks-e255d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdXT_2Ee7ZF6mPASgnx5n3-Vv7gfM-5g',
    appId: '1:408784567402:ios:c5085d66920a774f489e13',
    messagingSenderId: '408784567402',
    projectId: 'busks-e255d',
    storageBucket: 'busks-e255d.appspot.com',
    iosClientId: '408784567402-8rh554se2907iikrrag9kp5nduels6p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.buskz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApdXT_2Ee7ZF6mPASgnx5n3-Vv7gfM-5g',
    appId: '1:408784567402:ios:c5085d66920a774f489e13',
    messagingSenderId: '408784567402',
    projectId: 'busks-e255d',
    storageBucket: 'busks-e255d.appspot.com',
    iosClientId: '408784567402-8rh554se2907iikrrag9kp5nduels6p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.buskz',
  );
}
